apiVersion: "v1"
kind: LimitRange
metadata:
  name: boutique-shared
spec:
  limits:
    - type: Pod
      max: 
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "20m"
        memory: "2Mi"

