# Default values for tenant-manager-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


namespace:
  name: saas-boutique

database:
  databaseName: tenantmanager
  username: saas
  password: redhat
  rootPassword: admin

backend:
  containerImagePath: quay.io/ecosystem-appeng/saas-tenant-manager-backend:latest

frontend:
  containerImagePath: quay.io/ecosystem-appeng/saas-tenant-manager-frontend:latest
