apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: boutique-tenant-deployer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: boutique-tenant-deployer-role
subjects:
- kind: ServiceAccount
  name: boutique-tenant-operator-controller-manager
  namespace: boutique-tenant-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boutique-tenant-deployer-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
