{{- $service := (lookup "v1" "Service" (include "adservice.namespace" .) "adservice") }}
{{- if not $service }}
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: {{ include "adservice.namespace" . }}
  {{- if include "adservice.keep" . }}
  annotations: 
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: adservice
    function: tenant
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
{{- end }}