apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boutique-shop-deployer-role
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
    apiGroups:
      - ''
      - apps
    resources:
      - deployments
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - services
