kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boutique-shop-deployer-role-binding
subjects:
  - kind: ServiceAccount
    name: boutique-shop-operator-controller-manager
    namespace: boutique-shop-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: boutique-shop-deployer-role
