# permissions for end users to edit boutiqueshops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: boutiqueshop-editor-role
rules:
- apiGroups:
  - demo.openshift.com
  resources:
  - boutiqueshops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.openshift.com
  resources:
  - boutiqueshops/status
  verbs:
  - get
