# permissions for end users to view hpascalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpascaler-viewer-role
rules:
- apiGroups:
  - demo.openshift.com
  resources:
  - hpascalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.openshift.com
  resources:
  - hpascalers/status
  verbs:
  - get
