# permissions for end users to edit hpascalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpascaler-editor-role
rules:
- apiGroups:
  - demo.openshift.com
  resources:
  - hpascalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.openshift.com
  resources:
  - hpascalers/status
  verbs:
  - get
