apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: boutique-shop-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: boutique-shop-operator
  name: boutique-silver
---
apiVersion: demo.openshift.com/v1alpha1
kind: BoutiqueShop
metadata:
  labels:
    app.kubernetes.io/name: boutique-silver
    app.kubernetes.io/instance: boutique-silver
    app.kubernetes.io/part-of: boutique-shop-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: boutique-shop-operator
  name: boutique-silver
  namespace: boutique-silver
spec:
  #loadGeneratorUsers: 2
  tier: silver