{{- $service := (lookup "v1" "Service" (include "cartservice.namespace" .) "cartservice") }}
{{- if not $service }}
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: {{ include "cartservice.namespace" . }}
  {{- if include "cartservice.keep" . }}
  annotations: 
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
{{- end }}