kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tenant-controller-route
  namespace: {{ .Values.namespace.name }}
spec:
  to:
    kind: Service
    name: tenant-controller-service
  port:
    targetPort: tenant-backend-port
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tenant-frontend-route
  namespace: {{ .Values.namespace.name }}
spec:
  to:
    kind: Service
    name: tenant-frontend-service
  port:
    targetPort: tenant-manager-frontend-port
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None