apiVersion: v1
kind: Service
metadata:
  name: tenant-controller-db-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: tenant-controller-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tenant-manager-backend
  ports:
    - protocol: TCP
      name: tenant-backend-port
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: tenant-frontend-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tenant-manager-frontend
  ports:
    - protocol: TCP
      name: tenant-manager-frontend-port
      port: 80
      targetPort: 3000
