apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: boutique-tenant-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Deploys Boutique Tenant Manager operator to provision multiple tenants
    in SaaS environment
  displayName: Boutique Tenant Manager
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - boutique
  - saas
  - tenant
  links:
  - name: Boutique Tenant Operator
    url: https://boutique-tenant-operator.domain
  maturity: alpha
  provider:
    name: RedHat Inc
    url: https://www.redhat.com
  version: 0.0.0

  # config/manifests/bases
