apiVersion: v1
kind: Namespace
metadata:
  name: boutique-free
---
apiVersion: demo.openshift.com/v1alpha1
kind: BoutiqueShop
metadata:
  name: boutique-free
  namespace: boutique-free
spec:
  tier: free
