apiVersion: v1
kind: ServiceAccount
metadata:
  name: boutique-${namespace}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boutique-${namespace}-privileged
subjects:
  - kind: ServiceAccount
    name: boutique-${namespace}
    namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
