FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5
RUN microdnf install wget gzip tar
RUN mkdir /tmp/ocp && cd /tmp/ocp && wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
RUN cd /tmp/ocp && tar -zxvf openshift-client-linux.tar.gz 
RUN cd /tmp/ocp && mv oc /usr/bin/oc && mv kubectl /usr/bin/kubectl
CMD  ["bash"]
