apiVersion: v1
kind: Secret
metadata:
  name: tenant-controller-mysql-password
  namespace: {{ .Values.namespace.name }}
type: opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.databasePassword }}
