apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-controller-sa
  namespace: {{ .Values.namespace.name }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-controller-role-{{ .Release.Name }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - create
      - delete
      - update
      - patch
      - watch
      - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-controller-role-binding-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-controller-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: tenant-controller-sa
    namespace: {{ .Values.namespace.name }}