{{- $deployment := (lookup "v1" "Deployment" (include "currencyservice.namespace" .) "currencyservice") }}
{{- if not $deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: {{ include "currencyservice.namespace" . }}
  {{- if include "currencyservice.keep" . }}
  annotations: 
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  selector:
    matchLabels:
      app: currencyservice
      function: backends
  template:
    metadata:
      labels:
        app: currencyservice
        function: backends
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      # securityContext:
      #   fsGroup: 10000
      #   runAsGroup: 10000
      #   runAsNonRoot: true
      #   runAsUser: 10000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
{{- end }}
