
{{- $deployment := (lookup "v1" "Deployment" (include "checkoutservice.namespace" .) "checkoutservice") }}
{{- if not $deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: {{ include "checkoutservice.namespace" . }}
  {{- if include "checkoutservice.keep" . }}
  annotations: 
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  selector:
    matchLabels:
      app: checkoutservice
      function: backends
  template:
    metadata:
      labels:
        app: checkoutservice
        function: backends
    spec:
      serviceAccountName: default
      # securityContext:
      #   fsGroup: 10000
      #   runAsGroup: 10000
      #   runAsNonRoot: true
      #   runAsUser: 10000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 5050
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.{{ include "ops.namespace" . }}.svc:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.{{ include "ops.namespace" . }}.svc:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.{{ include "utilities.namespace" . }}.svc:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.{{ include "utilities.namespace" . }}.svc:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.{{ include "utilities.namespace" . }}.svc:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.{{ include "ops.namespace" . }}.svc:7070"
          - name: DISABLE_STATS
            value: "1"
          - name: DISABLE_TRACING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
{{- end }}