{{- $service := (lookup "v1" "Service" (include "ops.namespace" .) "productcatalogservice") }}
{{- if not $service }}
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: {{ include "ops.namespace" . }}
  {{- if include "productcatalogservice.keep" . }}
  annotations: 
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
    function: backends
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
{{- end }}