---
name: Deploy New Chart

on:
  workflow_dispatch:

env:
  HELM_REPO_URL: "https://rhecosystemappeng.github.io/saas-ecommerce-boutique-shop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Package and deploy a new chart version
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Get chart details
        id: chart_details
        run: |
          echo "chart_name=$(cat ./tenant-manager-chart/Chart.yaml | grep 'name:' | cut -c 7-)" >> $GITHUB_ENV
          echo "chart_version=$(cat ./tenant-manager-chart/Chart.yaml | grep 'version:' | cut -c 10-)" >> $GITHUB_ENV
          echo "file_name=${chart_name}-${chart_version}.tgz" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v1.1

      - name: Lint chart
        run: helm lint tenant-manager-chart

      - name: Package chart
        run: |
          helm package tenant-manager-chart
          mv ${{ env.file_name }} release.tgz

      - name: GH-Pages checkout
        run: git checkout gh-pages

      - name: Update repository index
        run: helm repo index --url ${{ env.HELM_REPO_URL }} .

      - name: Deploy new chart
        run: |
          mv release.tgz ${{ env.file_name }}
          git add ${{ env.file_name }}
          git add index.yaml
          git commit -m "chore: deployed ${{ env.file_name }}"
          git push
