---
name: Deploy New Chart

on:
  workflow_dispatch:
    inputs:

env:
  HELM_REPO_URL: "https://rhecosystemappeng.github.io/saas-ecommerce-boutique-shop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Package and deploy a new chart version
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Get chart name
        id: chart_name
        run: echo "::set-output name=name::$(cat ./tenant-manager-chart/Chart.yaml | grep 'name:' | cut -c 7-)"

      - name: Get chart version
        id: chart_version
        run: echo "::set-output name=name::$(cat ./tenant-manager-chart/Chart.yaml | grep 'version:' | cut -c 10-)"

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v1.1

      - name: Lint chart
        run: helm lint tenant-manager-chart

      - name: Package chart
        run: helm package tenant-manager-chart

      - name: GH-Pages checkout
        run: git checkout gh-pages

      - name: Update repository index
        run: helm repo index --url ${{ env.HELM_REPO_URL }} .

      - name: Deploy new chart
        run: |
          git add ${{ steps.chart_name.outputs.name }}-${{ steps.chart_name.outputs.chart_version }}.tgz
          git add index.yaml
          git commit -m "chore: deployed ${{ steps.chart_name.outputs.name }} ${{ steps.chart_name.outputs.chart_version }}"
          git push