name: Tenant Manager Backend image build and push to Quay
on:
  pull_request:
    types: [opened, edited, closed]
    branches: [ "main" ]
env:
  IMAGE_REGISTRY: quay.io
  IMAGE_REPOSITORY: ecosystem-appeng
  IMAGE_NAME: saas-tenant-manager-backend
jobs:
  build-image-and-push-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Maven
      run: sudo apt install -y maven
    - name: Maven clean 
      run: mvn -f ./tenant-manager-backend/pom.xml clean install -DskipTests
    - name: Build and publish docker image
      run: |
        BUILD_VERSION=latest
        echo Build version is: ${BUILD_VERSION}
        IMAGE_FULL=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${BUILD_VERSION}
        echo Building image: ${IMAGE_FULL}
        docker login "${{ env.IMAGE_REGISTRY }}" --username="${{ secrets.REGISTRY_USERNAME }}" --password="${{ secrets.REGISTRY_PASSWORD }}"

        docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t ${IMAGE_FULL} ./tenant-manager-backend
        docker push ${IMAGE_FULL}
  build-image-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and publish docker image
      env:
        IMAGE_NAME: saas-tenant-manager-frontend
      run: |
        BUILD_VERSION=latest
        echo Build version is: ${BUILD_VERSION}
        IMAGE_FULL=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${BUILD_VERSION}
        echo Building image: ${IMAGE_FULL}
        docker login "${{ env.IMAGE_REGISTRY }}" --username="${{ secrets.REGISTRY_USERNAME }}" --password="${{ secrets.REGISTRY_PASSWORD }}"

        docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t ${IMAGE_FULL} ./tenant-manager-frontend
        docker push ${IMAGE_FULL}
