name: Tenant Manager Backend image build and push to Quay
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_REGISTRRY: quay.io
  IMAGE_REPOSITORY: ecosystem-appeng
  IMAGE_NAME: saas-tenant-manager-backend
jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Maven
      run: |
        sudo apt install -y maven
    - name: Change working directory
      run: |
        cd ./tenant-manager-backend
    - name: Maven Clean
      run: |
        mvn clean install -DskipTests
    - name: Build and publish docker image
      run: |
        BUILD_VERSION=${{  github.ref_name }}
        echo Build version is: ${BUILD_VERSION}
        IMAGE_FULL=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${BUILD_VERSION}
        echo Building image: ${IMAGE_FULL}
        docker login --username="${{ secrets.REGISTRY_USERNAME }}" --password="${{ secrets.REGISTRY_PASSWORD }}" ${{ env.IMAGE_REGISTRY }}

        docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t ${IMAGE_FULL} .
        docker push ${IMAGE_FULL}
