apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    metadata:
      labels:
        module: event-display
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          name: user-container
          resources:
            limits:
              memory: 200Mi
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: provisioner-trigger
spec:
  broker: default
  filter:
    attributes:
      type: org.acme.saas.provisioner.event.NewTenantRequest
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: tenant-provisioner
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: provisioner-binding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: tenant-provisioner
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default