apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-provisioner-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - create
      - delete
      - update
      - watch
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-provisioner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-provisioner-role
subjects:
  - kind: ServiceAccount
    name: tenant-provisioner
    namespace: saas-provisioner